#include <stdlib.h>
#include "../tokens.h"
#include "tokens.h"

const char* const tifileutils_tokens_85_7E[0x012 + 2] = {
    /* Highest token in list */ (const char *const) 0x012,
    /* 00 */ "Sequential",
    /* 01 */ "Simul",
    /* 02 */ "PolarGC",
    /* 03 */ "RectGC",
    /* 04 */ "CoordOn",
    /* 05 */ "CoordOff",
    /* 06 */ "Connected",
    /* 07 */ "Dot",
    /* 08 */ "AxesOn",
    /* 09 */ "AxesOff",
    /* 0A */ "GridOn",
    /* 0B */ "GridOff",
    /* 0C */ "LabelOn",
    /* 0D */ "LabelOff",
    /* 0E */ "Web",
    /* 0F */ "Time",
    /* 10 */ "uvAxes",
    /* 11 */ "vwAxes",
    /* 12 */ "uwAxes",
};

const char* const tifileutils_tokens_85[0x0100] = {
    /* 00 */ NULL,
    /* 01 */ TITOKEN_TRIANGLE "Rec",
    /* 02 */ TITOKEN_TRIANGLE "Pol",
    /* 03 */ TITOKEN_TRIANGLE "Cyl",
    /* 04 */ TITOKEN_TRIANGLE "Sph",
    /* 05 */ TITOKEN_TRIANGLE "DMS",
    /* 06 */ TITOKEN_TRIANGLE "Bin",
    /* 07 */ TITOKEN_TRIANGLE "Hex",
    /* 08 */ TITOKEN_TRIANGLE "Oct",
    /* 09 */ TITOKEN_TRIANGLE "Dec",
    /* 0A */ TITOKEN_TRIANGLE "Frac",
    /* 0B */ TITOKEN_ARROW,
    /* 0C */ "[",
    /* 0D */ "]",
    /* 0E */ "{",
    /* 0F */ "}",
    /* 10 */ "(",
    /* 11 */ ")",
    /* 12 */ "round(",
    /* 13 */ "max",
    /* 14 */ "min",
    /* 15 */ "mod",
    /* 16 */ "cross",
    /* 17 */ "dot",
    /* 18 */ "aug",
    /* 19 */ "rSwap",
    /* 1A */ "rAdd",
    /* 1B */ "multR",
    /* 1C */ "mRAdd",
    /* 1D */ "sub",
    /* 1E */ "lcm",
    /* 1F */ "gcd",
    /* 20 */ "simult",
    /* 21 */ "inter",
    /* 22 */ "pEval",
    /* 23 */ "randM",
    /* 24 */ "seq",
    /* 25 */ "evalF",
    /* 26 */ "fnInt",
    /* 27 */ "arc",
    /* 28 */ "fMin",
    /* 29 */ "fMax",
    /* 2A */ "der1",
    /* 2B */ "der2",
    /* 2C */ "nDer",
    /* 2D */ NULL,
    /* 2E */ TITOKEN_ANGLE,
    /* 2F */ ",",
    /* 30 */ "or",
    /* 31 */ "xor",
    /* 32 */ NULL,
    /* 33 */ NULL,
    /* 34 */ NULL,
    /* 35 */ NULL,
    /* 36 */ NULL,
    /* 37 */ NULL,
    /* 38 */ NULL,
    /* 39 */ NULL,
    /* 3A */ NULL,
    /* 3B */ NULL,
    /* 3C */ NULL,
    /* 3D */ NULL,
    /* 3E */ NULL,
    /* 3F */ "=",
    /* 40 */ "and",
    /* 41 */ "rand",
    /* 42 */ TITOKEN_PI,
    /* 43 */ "getKy",
    /* 44 */ NULL,
    /* 45 */ "%",
    /* 46 */ "!",
    /* 47 */ TITOKEN_SUB_r,
    /* 48 */ TITOKEN_DEGREE,
    /* 49 */ TITOKEN_SUP_N_ONE,
    /* 4A */ TITOKEN_SUP_TWO,
    /* 4B */ TITOKEN_SUP_T,
    /* 4C */ "Menu",
    /* 4D */ "P2Reg",
    /* 4E */ "P3Reg",
    /* 4F */ "P4Reg",
    /* 50 */ "==",
    /* 51 */ "<",
    /* 52 */ ">",
    /* 53 */ TITOKEN_LTE,
    /* 54 */ TITOKEN_GTE,
    /* 55 */ TITOKEN_NOT_EQUAL,
    /* 56 */ "Radian",
    /* 57 */ "Degree",
    /* 58 */ "Normal",
    /* 59 */ "Sci",
    /* 5A */ "Eng",
    /* 5B */ "Float",
    /* 5C */ "Fix",
    /* 5D */ "RectV",
    /* 5E */ "CylV",
    /* 5F */ "SphereV",
    /* 60 */ "+",
    /* 61 */ "-",
    /* 62 */ "Func",
    /* 63 */ "Param",
    /* 64 */ "Pol",
    /* 65 */ "DifEq",
    /* 66 */ "Bin",
    /* 67 */ "Oct",
    /* 68 */ "Hex",
    /* 69 */ "Dec",
    /* 6A */ "RectC",
    /* 6B */ "PolarC",
    /* 6C */ "dxDer1",
    /* 6D */ "dxNDer",
    /* 6E */ ":",
    /* 6F */ "",
    /* 70 */ "*",
    /* 71 */ "/",
    /* 72 */ "SeqG",
    /* 73 */ "SimulG",
    /* 74 */ "PolarGC",
    /* 75 */ "RectGC",
    /* 76 */ "CoordOn",
    /* 77 */ "CoordOff",
    /* 78 */ "DrawLine",
    /* 79 */ "DrawDot",
    /* 7A */ "AxesOn",
    /* 7B */ "AxesOff",
    /* 7C */ "GridOn",
    /* 7D */ "GridOff",
    /* 7E */ "LabelOn",
    /* 7F */ "LabelOff",
    /* 80 */ "nPr",
    /* 81 */ "nCr",
    /* 82 */ "Trace",
    /* 83 */ "ClDrw",
    /* 84 */ "ZStd",
    /* 85 */ "ZTrig",
    /* 86 */ "ZFit",
    /* 87 */ "ZIn",
    /* 88 */ "ZOut",
    /* 89 */ "ZSqr",
    /* 8A */ "ZInt",
    /* 8B */ "ZPrev",
    /* 8C */ "ZDecm",
    /* 8D */ "ZRcl",
    /* 8E */ NULL,
    /* 8F */ "DrawF",
    /* 90 */ "FnOn",
    /* 91 */ "FnOff",
    /* 92 */ "StPic",
    /* 93 */ "RcPic",
    /* 94 */ "StGDB",
    /* 95 */ "RcGDB",
    /* 96 */ "Line",
    /* 97 */ "Vert",
    /* 98 */ "PtOn",
    /* 99 */ "PtOff",
    /* 9A */ "PtChg",
    /* 9B */ "Shade",
    /* 9C */ "Circl",
    /* 9D */ "Axes",
    /* 9E */ "TanLn",
    /* 9F */ "DrInv",
    /* A0 */ TITOKEN_SQRT,
    /* A1 */ "-",
    /* A2 */ "abs",
    /* A3 */ "iPart",
    /* A4 */ "fPart",
    /* A5 */ "int",
    /* A6 */ "ln",
    /* A7 */ TITOKEN_e "^",
    /* A8 */ "log",
    /* A9 */ TITOKEN_SUB_TEN "^",
    /* AA */ "sin",
    /* AB */ "sin" TITOKEN_SUP_N_ONE,
    /* AC */ "cos",
    /* AD */ "cos" TITOKEN_SUP_N_ONE,
    /* AE */ "tan",
    /* AF */ "tan" TITOKEN_SUP_N_ONE,
    /* B0 */ "sinh",
    /* B1 */ "sinh" TITOKEN_SUP_N_ONE,
    /* B2 */ "cosh",
    /* B3 */ "cosh" TITOKEN_SUP_N_ONE,
    /* B4 */ "tanh",
    /* B5 */ "tanh" TITOKEN_SUP_N_ONE,
    /* B6 */ "sign",
    /* B7 */ "det",
    /* B8 */ "ident",
    /* B9 */ "unitV",
    /* BA */ "norm",
    /* BB */ "rnorm",
    /* BC */ "cnorm",
    /* BD */ "ref",
    /* BE */ "rref",
    /* BF */ "dim",
    /* C0 */ "dimL",
    /* C1 */ "sum",
    /* C2 */ "prod",
    /* C3 */ "sortA",
    /* C4 */ "sortD",
    /* C5 */ "li" TITOKEN_TRIANGLE "vc",
    /* C6 */ "vc" TITOKEN_TRIANGLE "li",
    /* C7 */ "lngth",
    /* C8 */ "conj",
    /* C9 */ "real",
    /* CA */ "imag",
    /* CB */ "angle",
    /* CC */ "not",
    /* CD */ "rotR",
    /* CE */ "rotL",
    /* CF */ "shftR",
    /* D0 */ "shftL",
    /* D1 */ "eigVl",
    /* D2 */ "eigVc",
    /* D3 */ "cond",
    /* D4 */ "poly",
    /* D5 */ "fcstx",
    /* D6 */ "fcsty",
    /* D7 */ "eval",
    /* D8 */ "If",
    /* D9 */ "Then",
    /* DA */ "Else",
    /* DB */ "While",
    /* DC */ "Repeat",
    /* DD */ "For",
    /* DE */ "End",
    /* DF */ "Return",
    /* E0 */ NULL,
    /* E1 */ NULL,
    /* E2 */ "Pause",
    /* E3 */ "Stop",
    /* E4 */ "IS>",
    /* E5 */ "DS<",
    /* E6 */ "Input",
    /* E7 */ "Prompt",
    /* E8 */ "InpSt",
    /* E9 */ "Disp",
    /* EA */ "DispG",
    /* EB */ "Outpt",
    /* EC */ "ClLCD",
    /* ED */ "Eq" TITOKEN_TRIANGLE "St",
    /* EE */ "St" TITOKEN_TRIANGLE "Eq",
    /* EF */ "Fill",
    /* F0 */ "^",
    /* F1 */ TITOKEN_XRT,
    /* F2 */ "Solver",
    /* F3 */ "OneVar",
    /* F4 */ "LinR",
    /* F5 */ "ExpR",
    /* F6 */ "LnR",
    /* F7 */ "PwrR",
    /* F8 */ "ShwSt",
    /* F9 */ "Hist",
    /* FA */ "xyLine",
    /* FB */ "Scatter",
    /* FC */ "SortX",
    /* FD */ "SortY",
    /* FE */ "LU",
    /* FF */ NULL,
};

const char *const *const TIFILEUTILS_TOKENS_85 = tifileutils_tokens_85;
