#ifndef TIFILEUTILS_TOKENS_H
#define TIFILEUTILS_TOKENS_H

#define TITOKEN_ARROW     "→"
#define TITOKEN_ALPHA     "𝛼"
#define TITOKEN_ANGLE     "∠"
#define TITOKEN_BETA      "𝛽"
#define TITOKEN_CHI       "𝜒"
#define TITOKEN_CUBERT    "∛"
#define TITOKEN_COPYRIGHT "©"
#define TITOKEN_DEGREE    "°"
#define TITOKEN_DELTA     "𝚫"
#define TITOKEN_delta     "𝛿"
#define TITOKEN_d         "d"
#define TITOKEN_DOT       "∙"
#define TITOKEN_DOT_SM    "⋅"
#define TITOKEN_E         "⋿"
#define TITOKEN_e         "𝑒"
#define TITOKEN_epsilon   "𝜖"
#define TITOKEN_F         "𝐅"
#define TITOKEN_FRACTION  "/"
#define TITOKEN_GAMMA     "𝛾"
#define TITOKEN_GTE       "≥"
#define TITOKEN_i         "𝑖"
#define TITOKEN_INFIN     "∞"
#define TITOKEN_INTEGRAL  "∫"
#define TITOKEN_LAMDA     "𝜆"
#define TITOKEN_LIST_L    "ʟ"
#define TITOKEN_LTE       "≤"
#define TITOKEN_MICRO     "µ"
#define TITOKEN_N         "𝐍"
#define TITOKEN_n         "𝑛"
#define TITOKEN_NOT_EQUAL "≠"
#define TITOKEN_OMEGA     "Ω"
#define TITOKEN_PHI       "ɸ"
#define TITOKEN_PI        "𝜋"
#define TITOKEN_PHAT      "p̂"
#define TITOKEN_RHO       "𝜌"
#define TITOKEN_SIGMA     "𝜎"
#define TITOKEN_SQRT      "√"
#define TITOKEN_SQUARE    "□"
#define TITOKEN_SHARP_S   "ß"
#define TITOKEN_SOLIDUS_R "\\"
#define TITOKEN_SUMMATION "∑" /* N-ARY SUMMATION */
#define TITOKEN_SUB_N_ONE "₋₁"
#define TITOKEN_SUB_ZERO  "₀"
#define TITOKEN_SUB_ONE   "₁"
#define TITOKEN_SUB_TWO   "₂"
#define TITOKEN_SUB_THREE "₃"
#define TITOKEN_SUB_FOUR  "₄"
#define TITOKEN_SUB_FIVE  "₅"
#define TITOKEN_SUB_SIX   "₆"
#define TITOKEN_SUB_SEVEN "₇"
#define TITOKEN_SUB_EIGHT "₈"
#define TITOKEN_SUB_NINE  "₉"
#define TITOKEN_SUB_TEN   "₁₀"
#define TITOKEN_SUB_r     "ᵣ"
#define TITOKEN_SUB_T     "ₜ"
#define TITOKEN_SUP_N_ONE "⁻¹"
#define TITOKEN_SUP_ZERO  "⁰"
#define TITOKEN_SUP_ONE   "¹"
#define TITOKEN_SUP_TWO   "²"
#define TITOKEN_SUP_THREE "³"
#define TITOKEN_SUP_FOUR  "⁴"
#define TITOKEN_SUP_FIVE  "⁵"
#define TITOKEN_SUP_SIX   "⁶"
#define TITOKEN_SUP_SEVEN "⁷"
#define TITOKEN_SUP_EIGHT "⁸"
#define TITOKEN_SUP_NINE  "⁹"
#define TITOKEN_SUP_TEN   "¹⁰"
#define TITOKEN_SUP_r     "ʳ"
#define TITOKEN_SUP_T     "ᵀ"
#define TITOKEN_SUP_X     "ˣ"
#define TITOKEN_TAU       "𝜏"
#define TITOKEN_THETA     "𝛳"
#define TITOKEN_TRIANGLE  "▶︎"
#define TITOKEN_TRIANGLEL "◀︎"
#define TITOKEN_Und       "⊔"
#define TITOKEN_XRT       "ˣ√"
#define TITOKEN_X_MEAN    "x̅"
#define TITOKEN_Y_MEAN    "y̅"

#define TITOKEN_ARROW_UP  "↑"
#define TITOKEN_ARROW_DOWN "↓"
#define TITOKEN_ARROW_UP_BOLD "⬆︎"
#define TITOKEN_ARROW_DOWN_BOLD "⬇︎"
#define TITOKEN_INVERT_EQUAL "⌸"

const char* const TI_TOKEN_LISTS[1 + 10];
const char* const TI_TOKEN_Y[1 + 10];
const char* const TI_TOKEN_STR[1 + 10];
const char* const TI_TOKEN_PIC[1 + 10];
const char* const TI_TOKEN_GDB[1 + 10];
const char* const TI_TOKEN_MATRIX[1 + 10];

#endif
