#include <stdlib.h>
#include "../tokens.h"
#include "tokens.h"

const char* const tifileutils_tokens_83_7E[19] = {
    /* 00 */ "Sequential",
    /* 01 */ "Simul",
    /* 02 */ "PolarGC",
    /* 03 */ "RectGC",
    /* 04 */ "CoordOn",
    /* 05 */ "CoordOff",
    /* 06 */ "Connected",
    /* 07 */ "Dot",
    /* 08 */ "AxesOn",
    /* 09 */ "AxesOff",
    /* 0A */ "GridOn",
    /* 0B */ "GridOff",
    /* 0C */ "LabelOn",
    /* 0D */ "LabelOff",
    /* 0E */ "Web",
    /* 0F */ "Time",
    /* A0 */ "uvAxes",
    /* A1 */ "vwAxes",
    /* A2 */ "uwAxes",
};

const char* const tifileutils_tokens_83_BB[92] = {
    /* 00 */ "npv(",
    /* 01 */ "irr(",
    /* 02 */ "bal(",
    /* 03 */ TITOKEN_EPSILON "Prn(",
    /* 04 */ TITOKEN_EPSILON "Int(",
    /* 05 */ TITOKEN_TRIANGLE "Nom(",
    /* 06 */ TITOKEN_TRIANGLE "Eff(",
    /* 07 */ "dbd(",
    /* 08 */ "lcm(",
    /* 09 */ "gcd(",
    /* 0A */ "randInt(",
    /* 0B */ "randBin(",
    /* 0C */ "sub(",
    /* 0D */ "stdDev(",
    /* 0E */ "variance(",
    /* 0F */ "inString(",
    /* 10 */ "normalcdf(",
    /* 11 */ "invNorm(",
    /* 12 */ "tcdf(",
    /* 13 */ TITOKEN_CHI TITOKEN_SUP_TWO "cdf(",
    /* 14 */ TITOKEN_F "cdf(",
    /* 15 */ "binompdf(",
    /* 16 */ "binomcdf(",
    /* 17 */ "poissonpdf(",
    /* 18 */ "poissoncdf(",
    /* 19 */ "geometpdf(",
    /* 1A */ "geometcdf(",
    /* 1B */ "normalpdf(",
    /* 1C */ "tpdf(",
    /* 1D */ TITOKEN_CHI TITOKEN_SUP_TWO "pdf(",
    /* 1E */ TITOKEN_F "pdf(",
    /* 1F */ "randNorm(",
    /* 20 */ "tvm_pmt",
    /* 21 */ "tvm_I%",
    /* 22 */ "tvm_PV",
    /* 23 */ "tvm_" TITOKEN_N,
    /* 24 */ "tvm_FV",
    /* 25 */ "conj(",
    /* 26 */ "real(",
    /* 27 */ "imag(",
    /* 28 */ "angle(",
    /* 29 */ "cumSum(",
    /* 2A */ "expr(",
    /* 2B */ "length(",
    /* 2C */ TITOKEN_DELTA "List(",
    /* 2D */ "ref(",
    /* 2E */ "rref(",
    /* 2F */ TITOKEN_TRIANGLE "Rect",
    /* 30 */ TITOKEN_TRIANGLE "Polar",
    /* 31 */ TITOKEN_e,
    /* 32 */ "SinReg ",
    /* 33 */ "Logistic ",
    /* 34 */ "LinRegTTest ",
    /* 35 */ "ShadeNorm(",
    /* 36 */ "Shade_t(",
    /* 37 */ "Shade" TITOKEN_CHI TITOKEN_SUP_TWO "(",
    /* 38 */ "Shade" TITOKEN_F "(",
    /* 39 */ "Matr" TITOKEN_TRIANGLE "list",
    /* 3A */ "List" TITOKEN_TRIANGLE "matr",
    /* 3B */ "Z-Test(",
    /* 3C */ "T-Test ",
    /* 3D */ "2-SampZTest(",
    /* 3E */ "1-PropZTest(",
    /* 3F */ "2-PropZTest(",
    /* 40 */ TITOKEN_CHI TITOKEN_SUP_TWO "-Test(",
    /* 41 */ "ZInterval ",
    /* 42 */ "2-SampZInt(",
    /* 43 */ "1-PropZInt(",
    /* 44 */ "2-PropZInt(",
    /* 45 */ "GraphStyle(",
    /* 46 */ "2-SampTTest ",
    /* 47 */ "2-Samp" TITOKEN_F "Test",
    /* 48 */ "TInterval ",
    /* 49 */ "2-SampTInt ",
    /* 4A */ "SetUpEditor ",
    /* 4B */ "PMT_End",
    /* 4C */ "PMT_Bgn",
    /* 4D */ "Real",
    /* 4E */ TITOKEN_SUB_r TITOKEN_e "^" TITOKEN_THETA TITOKEN_i,
    /* 4F */ "a+b" TITOKEN_i,
    /* 50 */ "ExprOn",
    /* 51 */ "ExprOff",
    /* 52 */ "ClrAllLists",
    /* 53 */ "GetCalc(",
    /* 54 */ "DelVar ",
    /* 55 */ "Equ" TITOKEN_TRIANGLE "String(",
    /* 56 */ "String" TITOKEN_TRIANGLE "Equ(",
    /* 57 */ "Clear_Entries",
    /* 58 */ "Select(",
    /* 59 */ "ANOVA(",
    /* 5A */ "ModBoxPlot",
    /* 5B */ "NormProbPlot",
};

const char* const tifileutils_tokens_83[] = {
    /* 00 */ NULL,
    /* 01 */ TITOKEN_TRIANGLE "DMS",
    /* 02 */ TITOKEN_TRIANGLE "Dec",
    /* 03 */ TITOKEN_TRIANGLE "Frac",
    /* 04 */ TITOKEN_ARROW,
    /* 05 */ "BoxPlot",
    /* 06 */ "[",
    /* 07 */ "]",
    /* 08 */ "{",
    /* 09 */ "}",
    /* 0A */ TITOKEN_SUB_r,
    /* 0B */ TITOKEN_DEGREE,
    /* 0C */ "",
    /* 0D */ "",
    /* 0E */ "",
    /* 0F */ "",
    /* 10 */ "(",
    /* 11 */ ")",
    /* 12 */ "round(",
    /* 13 */ "pxl-Test(",
    /* 14 */ "augment(",
    /* 15 */ "rowSwap(",
    /* 16 */ "row+(",
    /* 17 */ "*row(",
    /* 18 */ "*row+(",
    /* 19 */ "max(",
    /* 1A */ "min(",
    /* 1B */ "R" TITOKEN_TRIANGLE "Pr(",
    /* 1C */ "R" TITOKEN_TRIANGLE "P" TITOKEN_THETA "(",
    /* 1D */ "P" TITOKEN_TRIANGLE "Rx(",
    /* 1E */ "P" TITOKEN_TRIANGLE "Ry(",
    /* 1F */ "median(",
    /* 20 */ "randM(",
    /* 21 */ "mean(",
    /* 22 */ "solve(",
    /* 23 */ "seq(",
    /* 24 */ "fnInt(",
    /* 25 */ "nDeriv(",
    /* 26 */ "",
    /* 27 */ "fMin(",
    /* 28 */ "fMax(",
    /* 29 */ "_",
    /* 2A */ "\"",
    /* 2B */ ",",
    /* 2C */ TITOKEN_i,
    /* 2D */ "!",
    /* 2E */ "CubicReg ",
    /* 2F */ "QuartReg ",
    /* 30 */ "0",
    /* 31 */ "1",
    /* 32 */ "2",
    /* 33 */ "3",
    /* 34 */ "4",
    /* 35 */ "5",
    /* 36 */ "6",
    /* 37 */ "7",
    /* 38 */ "8",
    /* 39 */ "9",
    /* 3A */ ".",
    /* 3B */ TITOKEN_E,
    /* 3C */ " or ",
    /* 3D */ " xor ",
    /* 3E */ ":",
    /* 3F */ "\n",
    /* 40 */ " and ",
    /* 41 */ "A",
    /* 42 */ "B",
    /* 43 */ "C",
    /* 44 */ "D",
    /* 45 */ "E",
    /* 46 */ "F",
    /* 47 */ "G",
    /* 48 */ "H",
    /* 49 */ "I",
    /* 4A */ "J",
    /* 4B */ "K",
    /* 4C */ "L",
    /* 4D */ "M",
    /* 4E */ "N",
    /* 4F */ "O",
    /* 50 */ "P",
    /* 51 */ "Q",
    /* 52 */ "R",
    /* 53 */ "S",
    /* 54 */ "T",
    /* 55 */ "U",
    /* 56 */ "V",
    /* 57 */ "W",
    /* 58 */ "X",
    /* 59 */ "Y",
    /* 5A */ "Z",
    /* 5B */ TITOKEN_THETA,
    /* 5C */ (const char *const) TI_TOKEN_MATRIX,
    /* 5D */ (const char *const) TI_TOKEN_LISTS,
    /* 5E */ NULL,
    /* 5F */ "prgm",
    /* 60 */ (const char *const) TI_TOKEN_PIC,
    /* 61 */ (const char *const) TI_TOKEN_GDB,
    /* 62 */ NULL,
    /* 63 */ NULL,
    /* 64 */ "Radian",
    /* 65 */ "Degree",
    /* 66 */ "Normal",
    /* 67 */ "Sci",
    /* 68 */ "Eng",
    /* 69 */ "Float",
    /* 6A */ "=",
    /* 6B */ "<",
    /* 6C */ ">",
    /* 6D */ "",
    /* 6E */ "",
    /* 6F */ "",
    /* 70 */ "+",
    /* 71 */ "-",
    /* 72 */ "Ans",
    /* 73 */ "Fix ",
    /* 74 */ "Horiz",
    /* 75 */ "Full",
    /* 76 */ "Func",
    /* 77 */ "Param",
    /* 78 */ "Polar",
    /* 79 */ "Seq",
    /* 7A */ "IndpntAuto",
    /* 7B */ "IndpntAsk",
    /* 7C */ "DependAuto",
    /* 7D */ "DependAsk",
    /* 7E */ (const char *const) tifileutils_tokens_83_7E,
    /* 7F */ "",
    /* 80 */ "",
    /* 81 */ "",
    /* 82 */ "*",
    /* 83 */ "/",
    /* 84 */ "Trace",
    /* 85 */ "ClrDraw",
    /* 86 */ "ZStandard",
    /* 87 */ "ZTrig",
    /* 88 */ "ZBox",
    /* 89 */ "Zoom In",
    /* 8A */ "Zoom Out",
    /* 8B */ "ZSquare",
    /* 8C */ "ZInteger",
    /* 8D */ "ZPrevious",
    /* 8E */ "ZDecimal",
    /* 8F */ "ZoomStat",
    /* 90 */ "ZoomRcl",
    /* 91 */ "PrintScreen",
    /* 92 */ "ZoomSto",
    /* 93 */ "Text(",
    /* 94 */ " nPr ",
    /* 95 */ " nCr ",
    /* 96 */ "FnOn ",
    /* 97 */ "FnOff ",
    /* 98 */ "StorePic ",
    /* 99 */ "RecallPic ",
    /* 9A */ "StoreGDB ",
    /* 9B */ "RecallGDB ",
    /* 9C */ "Line(",
    /* 9D */ "Vertical ",
    /* 9E */ "Pt-On(",
    /* 9F */ "Pt-Off(",
    /* A0 */ "Pt-Change(",
    /* A1 */ "Pxl-On(",
    /* A2 */ "Pxl-Off(",
    /* A3 */ "Pxl-Change(",
    /* A4 */ "Shade(",
    /* A5 */ "Circle(",
    /* A6 */ "Horizontal ",
    /* A7 */ "Tangent(",
    /* A8 */ "DrawInv ",
    /* A9 */ "DrawF ",
    /* AA */ NULL,
    /* AB */ "rand",
    /* AC */ TITOKEN_PI,
    /* AD */ "getKey",
    /* AE */ "'",
    /* AF */ "?",
    /* B0 */ "-",
    /* B1 */ "int(",
    /* B2 */ "abs(",
    /* B3 */ "det(",
    /* B4 */ "identity(",
    /* B5 */ "dim(",
    /* B6 */ "sum(",
    /* B7 */ "prod(",
    /* B8 */ "not(",
    /* B9 */ "iPart(",
    /* BA */ "fPart(",
    /* BB */ (const char *const) tifileutils_tokens_83_BB,
    /* BC */ TITOKEN_SQRT "(",
    /* BD */ TITOKEN_CUBERT "(",
    /* BE */ "ln_(",
    /* BF */ TITOKEN_e "^(",
    /* C0 */ "log(",
    /* C1 */ TITOKEN_SUB_TEN "^(",
    /* C2 */ "sin(",
    /* C3 */ "sin" TITOKEN_SUP_N_ONE "(",
    /* C4 */ "cos(",
    /* C5 */ "cos" TITOKEN_SUP_N_ONE "(",
    /* C6 */ "tan(",
    /* C7 */ "tan" TITOKEN_SUP_N_ONE "(",
    /* C8 */ "sinh(",
    /* C9 */ "sinh" TITOKEN_SUP_N_ONE "(",
    /* CA */ "cosh(",
    /* CB */ "cosh" TITOKEN_SUP_N_ONE "(",
    /* CC */ "tanh(",
    /* CD */ "tanh" TITOKEN_SUP_N_ONE "(",
    /* CE */ "If ",
    /* CF */ "Then",
    /* D0 */ "Else",
    /* D1 */ "While ",
    /* D2 */ "Repeat ",
    /* D3 */ "For(",
    /* D4 */ "End",
    /* D5 */ "Return",
    /* D6 */ "Lbl ",
    /* D7 */ "Goto ",
    /* D8 */ "Pause ",
    /* D9 */ "Stop",
    /* DA */ "IS>(",
    /* DB */ "DS>(",
    /* DC */ "Input ",
    /* DD */ "Prompt ",
    /* DE */ "Disp ",
    /* DF */ "DispGraph",
    /* E0 */ "Output(",
    /* E1 */ "ClrHome",
    /* E2 */ "Fill(",
    /* E3 */ "SortA(",
    /* E4 */ "SortD(",
    /* E5 */ "DispTable",
    /* E6 */ "Menu(",
    /* E7 */ "Send(",
    /* E8 */ "Get(",
    /* E9 */ "PlotsOn ",
    /* EA */ "PlotsOff ",
    /* EB */ TITOKEN_LIST_L,
    /* EC */ "Plot1(",
    /* ED */ "Plot2(",
    /* EE */ "Plot3(",
    /* EF */ NULL,
    /* F0 */ "^",
    /* F1 */ TITOKEN_XRT,
    /* F2 */ "1-Var_Stats ",
    /* F3 */ "2-Var_Stats ",
    /* F4 */ "LinReg(a+bx) ",
    /* F5 */ "ExpReg ",
    /* F6 */ "LnReg ",
    /* F7 */ "PwrReg ",
    /* F8 */ "Med-Med ",
    /* F9 */ "QuadReg ",
    /* FA */ "ClrList ",
    /* FB */ "ClrTable",
    /* FC */ "Histogram",
    /* FD */ "xyLine",
    /* FE */ "Scatter",
    /* FF */ "LinReg(ax+b)",
};
