#include <stdlib.h>
#include "../tokens.h"
#include "tokens.h"

const char* const tifileutils_tokens_83_5E[0x081 + 2] = {
    /* Highest token in list */ (const char *const) 0x081,
        /* 00 */ NULL,
        /* 01 */ NULL,
        /* 02 */ NULL,
        /* 03 */ NULL,
        /* 04 */ NULL,
        /* 05 */ NULL,
        /* 06 */ NULL,
        /* 07 */ NULL,
        /* 08 */ NULL,
        /* 09 */ NULL,
        /* 0A */ NULL,
        /* 0B */ NULL,
        /* 0C */ NULL,
        /* 0D */ NULL,
        /* 0E */ NULL,
        /* 0F */ NULL,
        /* 10 */ "Y" TITOKEN_SUB_ONE,
        /* 11 */ "Y" TITOKEN_SUB_TWO,
        /* 12 */ "Y" TITOKEN_SUB_THREE,
        /* 13 */ "Y" TITOKEN_SUB_FOUR,
        /* 14 */ "Y" TITOKEN_SUB_FIVE,
        /* 15 */ "Y" TITOKEN_SUB_SIX,
        /* 16 */ "Y" TITOKEN_SUB_SEVEN,
        /* 17 */ "Y" TITOKEN_SUB_EIGHT,
        /* 18 */ "Y" TITOKEN_SUB_NINE,
        /* 19 */ "Y" TITOKEN_SUB_ZERO,
        /* 1A */ NULL,
        /* 1B */ NULL,
        /* 1C */ NULL,
        /* 1D */ NULL,
        /* 1E */ NULL,
        /* 1F */ NULL,
        /* 20 */ "X" TITOKEN_SUB_ONE,
        /* 21 */ "Y" TITOKEN_SUB_ONE,
        /* 22 */ "X" TITOKEN_SUB_TWO,
        /* 23 */ "Y" TITOKEN_SUB_TWO,
        /* 24 */ "X" TITOKEN_SUB_THREE,
        /* 25 */ "Y" TITOKEN_SUB_THREE,
        /* 26 */ "X" TITOKEN_SUB_FOUR,
        /* 27 */ "Y" TITOKEN_SUB_FOUR,
        /* 28 */ "X" TITOKEN_SUB_FIVE,
        /* 29 */ "Y" TITOKEN_SUB_FIVE,
        /* 2A */ "X" TITOKEN_SUB_SIX,
        /* 2B */ "Y" TITOKEN_SUB_SIX,
        /* 2C */ NULL,
        /* 2D */ NULL,
        /* 2E */ NULL,
        /* 2F */ NULL,
        /* 30 */ NULL,
        /* 31 */ NULL,
        /* 32 */ NULL,
        /* 33 */ NULL,
        /* 34 */ NULL,
        /* 35 */ NULL,
        /* 36 */ NULL,
        /* 37 */ NULL,
        /* 38 */ NULL,
        /* 39 */ NULL,
        /* 3A */ NULL,
        /* 3B */ NULL,
        /* 3C */ NULL,
        /* 3D */ NULL,
        /* 3E */ NULL,
        /* 3F */ NULL,
        /* 40 */ TITOKEN_SUB_r TITOKEN_SUB_ONE,
        /* 41 */ TITOKEN_SUB_r TITOKEN_SUB_TWO,
        /* 42 */ TITOKEN_SUB_r TITOKEN_SUB_THREE,
        /* 43 */ TITOKEN_SUB_r TITOKEN_SUB_FOUR,
        /* 44 */ TITOKEN_SUB_r TITOKEN_SUB_FIVE,
        /* 45 */ TITOKEN_SUB_r TITOKEN_SUB_SIX,
        /* 46 */ NULL,
        /* 47 */ NULL,
        /* 48 */ NULL,
        /* 49 */ NULL,
        /* 4A */ NULL,
        /* 4B */ NULL,
        /* 4C */ NULL,
        /* 4D */ NULL,
        /* 4E */ NULL,
        /* 4F */ NULL,
        /* 50 */ NULL,
        /* 51 */ NULL,
        /* 52 */ NULL,
        /* 53 */ NULL,
        /* 54 */ NULL,
        /* 55 */ NULL,
        /* 56 */ NULL,
        /* 57 */ NULL,
        /* 58 */ NULL,
        /* 59 */ NULL,
        /* 5A */ NULL,
        /* 5B */ NULL,
        /* 5C */ NULL,
        /* 5D */ NULL,
        /* 5E */ NULL,
        /* 5F */ NULL,
        /* 60 */ NULL,
        /* 61 */ NULL,
        /* 62 */ NULL,
        /* 63 */ NULL,
        /* 64 */ NULL,
        /* 65 */ NULL,
        /* 66 */ NULL,
        /* 67 */ NULL,
        /* 68 */ NULL,
        /* 69 */ NULL,
        /* 6A */ NULL,
        /* 6B */ NULL,
        /* 6C */ NULL,
        /* 6D */ NULL,
        /* 6E */ NULL,
        /* 6F */ NULL,
        /* 70 */ NULL,
        /* 71 */ NULL,
        /* 72 */ NULL,
        /* 73 */ NULL,
        /* 74 */ NULL,
        /* 75 */ NULL,
        /* 76 */ NULL,
        /* 77 */ NULL,
        /* 78 */ NULL,
        /* 79 */ NULL,
        /* 7A */ NULL,
        /* 7B */ NULL,
        /* 7C */ NULL,
        /* 7D */ NULL,
        /* 7E */ NULL,
        /* 7F */ NULL,
        /* 80 */ "u",
        /* 81 */ "v",
};

const char* const tifileutils_tokens_83_62[0x03C + 2] = {
    /* Highest token in list */ (const char *const) 0x03C,
    /* 00 */ NULL,
    /* 01 */ "RegEq",
    /* 02 */ "n",
    /* 03 */ TITOKEN_X_MEAN,
    /* 04 */ TITOKEN_SUMMATION "x",
    /* 05 */ TITOKEN_SUMMATION "x" TITOKEN_SUP_TWO,
    /* 06 */ "Sx",
    /* 07 */ TITOKEN_SIGMA "x",
    /* 08 */ "minX",
    /* 09 */ "maxX",
    /* 0A */ "minY",
    /* 0B */ "maxY",
    /* 0C */ TITOKEN_Y_MEAN,
    /* 0D */ TITOKEN_SUMMATION "y",
    /* 0E */ TITOKEN_SUMMATION "y" TITOKEN_SUP_TWO,
    /* 0F */ "Sy",
    /* 10 */ TITOKEN_SIGMA "y",
    /* 11 */ TITOKEN_SUMMATION "xy",
    /* 12 */ "r",
    /* 13 */ "Med",
    /* 14 */ "Q" TITOKEN_SUB_ONE,
    /* 15 */ "Q" TITOKEN_SUB_THREE,
    /* 16 */ "a",
    /* 17 */ "b",
    /* 18 */ "c",
    /* 19 */ "d",
    /* 1A */ "e",
    /* 1B */ "x" TITOKEN_SUB_ONE,
    /* 1C */ "x" TITOKEN_SUB_TWO,
    /* 1D */ "x" TITOKEN_SUB_THREE,
    /* 1E */ "y" TITOKEN_SUB_ONE,
    /* 1F */ "y" TITOKEN_SUB_TWO,
    /* 20 */ "y" TITOKEN_SUB_THREE,
    /* 21 */ TITOKEN_n,
    /* 22 */ "p",
    /* 23 */ "z",
    /* 24 */ "t",
    /* 25 */ TITOKEN_CHI TITOKEN_SUB_TWO,
    /* 26 */ TITOKEN_F,
    /* 27 */ "df",
    /* 28 */ TITOKEN_PHAT,
    /* 29 */ TITOKEN_PHAT TITOKEN_SUB_ONE,
    /* 2A */ TITOKEN_PHAT TITOKEN_SUB_TWO,
    /* 2B */ TITOKEN_X_MEAN TITOKEN_SUB_ONE,
    /* 2C */ "Sx" TITOKEN_SUB_ONE,
    /* 2D */ "n" TITOKEN_SUB_ONE,
    /* 2E */ TITOKEN_X_MEAN TITOKEN_SUB_TWO,
    /* 2F */ "Sx" TITOKEN_SUB_TWO,
    /* 30 */ "n" TITOKEN_SUB_TWO,
    /* 31 */ "Sxp",
    /* 32 */ "lower",
    /* 33 */ "upper",
    /* 34 */ "s",
    /* 35 */ "r" TITOKEN_SUP_TWO,
    /* 36 */ "R" TITOKEN_SUP_TWO,
    /* 37 */ "df",
    /* 38 */ "SS",
    /* 39 */ "MS",
    /* 3A */ "df",
    /* 3B */ "SS",
    /* 3C */ "MS",
};

const char* const tifileutils_tokens_83_63[0x031 + 2] = {
    /* Highest token in list */ (const char *const) 0x031,
    /* 00 */ "ZXscl",
    /* 01 */ "ZYscl",
    /* 02 */ "Xscl",
    /* 03 */ "Yscl",
    /* 04 */ "U" TITOKEN_n "Start",
    /* 05 */ "V" TITOKEN_n "Start",
    /* 06 */ "U" TITOKEN_n TITOKEN_SUB_N_ONE,
    /* 07 */ "V" TITOKEN_n TITOKEN_SUB_N_ONE,
    /* 08 */ "ZU" TITOKEN_n "Start",
    /* 09 */ "ZV" TITOKEN_n "Start",
    /* 0A */ "Xmin",
    /* 0B */ "Xmax",
    /* 0C */ "Ymin",
    /* 0D */ "Ymax",
    /* 0E */ "Tmin",
    /* 0F */ "Tmax",
    /* 10 */ TITOKEN_THETA "min",
    /* 11 */ TITOKEN_THETA "max",
    /* 12 */ "ZXmin",
    /* 13 */ "ZXmax",
    /* 14 */ "ZYmin",
    /* 15 */ "ZYmax",
    /* 16 */ "Z" TITOKEN_THETA "min",
    /* 17 */ "Z" TITOKEN_THETA "max",
    /* 18 */ "ZTmin",
    /* 19 */ "ZTmax",
    /* 1A */ "TblMin",
    /* 1B */ TITOKEN_n "Min",
    /* 1C */ "Z" TITOKEN_n "Min",
    /* 1D */ TITOKEN_n "Max",
    /* 1E */ "Z" TITOKEN_n "Max",
    /* 1F */ TITOKEN_n "Start",
    /* 20 */ "Z" TITOKEN_n "Start",
    /* 21 */ TITOKEN_DELTA "Tbl",
    /* 22 */ "Tstep",
    /* 23 */ TITOKEN_THETA "step",
    /* 24 */ "ZTstep",
    /* 25 */ "Z" TITOKEN_THETA "step",
    /* 26 */ TITOKEN_DELTA "X",
    /* 27 */ TITOKEN_DELTA "Y",
    /* 28 */ "XFact",
    /* 29 */ "YFact",
    /* 2A */ "TblInput",
    /* 2B */ TITOKEN_N,
    /* 2C */ "I%",
    /* 2D */ "PV",
    /* 2E */ "PMT",
    /* 2F */ "FV",
    /* 30 */ "Xres",
    /* 31 */ "ZXres",
};

const char* const tifileutils_tokens_83_7E[0x012 + 2] = {
    /* Highest token in list */ (const char *const) 0x012,
    /* 00 */ "Sequential",
    /* 01 */ "Simul",
    /* 02 */ "PolarGC",
    /* 03 */ "RectGC",
    /* 04 */ "CoordOn",
    /* 05 */ "CoordOff",
    /* 06 */ "Connected",
    /* 07 */ "Dot",
    /* 08 */ "AxesOn",
    /* 09 */ "AxesOff",
    /* 0A */ "GridOn",
    /* 0B */ "GridOff",
    /* 0C */ "LabelOn",
    /* 0D */ "LabelOff",
    /* 0E */ "Web",
    /* 0F */ "Time",
    /* 10 */ "uvAxes",
    /* 11 */ "vwAxes",
    /* 12 */ "uwAxes",
};

const char* const tifileutils_tokens_83_BB[0x0CA + 2] = {
    /* Highest token in list */ (const char *const) 0x0CA,
    /* 00 */ "npv(",
    /* 01 */ "irr(",
    /* 02 */ "bal(",
    /* 03 */ TITOKEN_SUMMATION "Prn(",
    /* 04 */ TITOKEN_SUMMATION "Int(",
    /* 05 */ TITOKEN_TRIANGLE "Nom(",
    /* 06 */ TITOKEN_TRIANGLE "Eff(",
    /* 07 */ "dbd(",
    /* 08 */ "lcm(",
    /* 09 */ "gcd(",
    /* 0A */ "randInt(",
    /* 0B */ "randBin(",
    /* 0C */ "sub(",
    /* 0D */ "stdDev(",
    /* 0E */ "variance(",
    /* 0F */ "inString(",
    /* 10 */ "normalcdf(",
    /* 11 */ "invNorm(",
    /* 12 */ "tcdf(",
    /* 13 */ TITOKEN_CHI TITOKEN_SUP_TWO "cdf(",
    /* 14 */ TITOKEN_F "cdf(",
    /* 15 */ "binompdf(",
    /* 16 */ "binomcdf(",
    /* 17 */ "poissonpdf(",
    /* 18 */ "poissoncdf(",
    /* 19 */ "geometpdf(",
    /* 1A */ "geometcdf(",
    /* 1B */ "normalpdf(",
    /* 1C */ "tpdf(",
    /* 1D */ TITOKEN_CHI TITOKEN_SUP_TWO "pdf(",
    /* 1E */ TITOKEN_F "pdf(",
    /* 1F */ "randNorm(",
    /* 20 */ "tvm_pmt",
    /* 21 */ "tvm_I%",
    /* 22 */ "tvm_PV",
    /* 23 */ "tvm_" TITOKEN_N,
    /* 24 */ "tvm_FV",
    /* 25 */ "conj(",
    /* 26 */ "real(",
    /* 27 */ "imag(",
    /* 28 */ "angle(",
    /* 29 */ "cumSum(",
    /* 2A */ "expr(",
    /* 2B */ "length(",
    /* 2C */ TITOKEN_DELTA "List(",
    /* 2D */ "ref(",
    /* 2E */ "rref(",
    /* 2F */ TITOKEN_TRIANGLE "Rect",
    /* 30 */ TITOKEN_TRIANGLE "Polar",
    /* 31 */ TITOKEN_e,
    /* 32 */ "SinReg ",
    /* 33 */ "Logistic ",
    /* 34 */ "LinRegTTest ",
    /* 35 */ "ShadeNorm(",
    /* 36 */ "Shade_t(",
    /* 37 */ "Shade" TITOKEN_CHI TITOKEN_SUP_TWO "(",
    /* 38 */ "Shade" TITOKEN_F "(",
    /* 39 */ "Matr" TITOKEN_TRIANGLE "list",
    /* 3A */ "List" TITOKEN_TRIANGLE "matr",
    /* 3B */ "Z-Test(",
    /* 3C */ "T-Test ",
    /* 3D */ "2-SampZTest(",
    /* 3E */ "1-PropZTest(",
    /* 3F */ "2-PropZTest(",
    /* 40 */ TITOKEN_CHI TITOKEN_SUP_TWO "-Test(",
    /* 41 */ "ZInterval ",
    /* 42 */ "2-SampZInt(",
    /* 43 */ "1-PropZInt(",
    /* 44 */ "2-PropZInt(",
    /* 45 */ "GraphStyle(",
    /* 46 */ "2-SampTTest ",
    /* 47 */ "2-Samp" TITOKEN_F "Test",
    /* 48 */ "TInterval ",
    /* 49 */ "2-SampTInt ",
    /* 4A */ "SetUpEditor ",
    /* 4B */ "PMT_End",
    /* 4C */ "PMT_Bgn",
    /* 4D */ "Real",
    /* 4E */ TITOKEN_SUB_r TITOKEN_e "^" TITOKEN_THETA TITOKEN_i,
    /* 4F */ "a+b" TITOKEN_i,
    /* 50 */ "ExprOn",
    /* 51 */ "ExprOff",
    /* 52 */ "ClrAllLists",
    /* 53 */ "GetCalc(",
    /* 54 */ "DelVar ",
    /* 55 */ "Equ" TITOKEN_TRIANGLE "String(",
    /* 56 */ "String" TITOKEN_TRIANGLE "Equ(",
    /* 57 */ "Clear_Entries",
    /* 58 */ "Select(",
    /* 59 */ "ANOVA(",
    /* 5A */ "ModBoxPlot",
    /* 5B */ "NormProbPlot",
    /* 5C */ NULL,
    /* 5D */ NULL,
    /* 5E */ NULL,
    /* 5F */ NULL,
    /* 60 */ NULL,
    /* 61 */ NULL,
    /* 62 */ NULL,
    /* 63 */ NULL,
    /* 64 */ NULL,
    /* 65 */ NULL,
    /* 66 */ NULL,
    /* 67 */ NULL,
    /* 68 */ NULL,
    /* 69 */ NULL,
    /* 6A */ NULL,
    /* 6B */ NULL,
    /* 6C */ NULL,
    /* 6D */ NULL,
    /* 6E */ NULL,
    /* 6F */ NULL,
    /* 70 */ NULL,
    /* 71 */ NULL,
    /* 72 */ NULL,
    /* 73 */ NULL,
    /* 74 */ NULL,
    /* 75 */ NULL,
    /* 76 */ NULL,
    /* 77 */ NULL,
    /* 78 */ NULL,
    /* 79 */ NULL,
    /* 7A */ NULL,
    /* 7B */ NULL,
    /* 7C */ NULL,
    /* 7D */ NULL,
    /* 7E */ NULL,
    /* 7F */ NULL,
    /* 80 */ NULL,
    /* 81 */ NULL,
    /* 82 */ NULL,
    /* 83 */ NULL,
    /* 84 */ NULL,
    /* 85 */ NULL,
    /* 86 */ NULL,
    /* 87 */ NULL,
    /* 88 */ NULL,
    /* 89 */ NULL,
    /* 8A */ NULL,
    /* 8B */ NULL,
    /* 8C */ NULL,
    /* 8D */ NULL,
    /* 8E */ NULL,
    /* 8F */ NULL,
    /* 90 */ NULL,
    /* 91 */ NULL,
    /* 92 */ NULL,
    /* 93 */ NULL,
    /* 94 */ NULL,
    /* 95 */ NULL,
    /* 96 */ NULL,
    /* 97 */ NULL,
    /* 98 */ NULL,
    /* 99 */ NULL,
    /* 9A */ NULL,
    /* 9B */ NULL,
    /* 9C */ NULL,
    /* 9D */ NULL,
    /* 9E */ NULL,
    /* 9F */ NULL,
    /* A0 */ NULL,
    /* A1 */ NULL,
    /* A2 */ NULL,
    /* A3 */ NULL,
    /* A4 */ NULL,
    /* A5 */ NULL,
    /* A6 */ NULL,
    /* A7 */ NULL,
    /* A8 */ NULL,
    /* A9 */ NULL,
    /* AA */ NULL,
    /* AB */ NULL,
    /* AC */ NULL,
    /* AD */ NULL,
    /* AE */ NULL,
    /* AF */ NULL,
    /* B0 */ "a",
    /* B1 */ "b",
    /* B2 */ "c",
    /* B3 */ "d",
    /* B4 */ "e",
    /* B5 */ "f",
    /* B6 */ "g",
    /* B7 */ "h",
    /* B8 */ "i",
    /* B9 */ "j",
    /* BA */ "k",
    /* BB */ "l",
    "~",
    /* BD */ "m",
    /* BE */ "n",
    /* BF */ "o",
    /* C0 */ "p",
    /* C1 */ "q",
    /* C2 */ "r",
    /* C3 */ "s",
    /* C4 */ "t",
    /* C5 */ "u",
    /* C6 */ "v",
    /* C7 */ "w",
    /* C8 */ "x",
    /* C9 */ "y",
    /* CA */ "z",
};

const char* const tifileutils_tokens_83[0x0100] = {
    /* 00 */ NULL,
    /* 01 */ TITOKEN_TRIANGLE "DMS",
    /* 02 */ TITOKEN_TRIANGLE "Dec",
    /* 03 */ TITOKEN_TRIANGLE "Frac",
    /* 04 */ TITOKEN_ARROW,
    /* 05 */ "BoxPlot",
    /* 06 */ "[",
    /* 07 */ "]",
    /* 08 */ "{",
    /* 09 */ "}",
    /* 0A */ TITOKEN_SUB_r,
    /* 0B */ TITOKEN_DEGREE,
    /* 0C */ "",
    /* 0D */ "",
    /* 0E */ "",
    /* 0F */ "",
    /* 10 */ "(",
    /* 11 */ ")",
    /* 12 */ "round(",
    /* 13 */ "pxl-Test(",
    /* 14 */ "augment(",
    /* 15 */ "rowSwap(",
    /* 16 */ "row+(",
    /* 17 */ "*row(",
    /* 18 */ "*row+(",
    /* 19 */ "max(",
    /* 1A */ "min(",
    /* 1B */ "R" TITOKEN_TRIANGLE "Pr(",
    /* 1C */ "R" TITOKEN_TRIANGLE "P" TITOKEN_THETA "(",
    /* 1D */ "P" TITOKEN_TRIANGLE "Rx(",
    /* 1E */ "P" TITOKEN_TRIANGLE "Ry(",
    /* 1F */ "median(",
    /* 20 */ "randM(",
    /* 21 */ "mean(",
    /* 22 */ "solve(",
    /* 23 */ "seq(",
    /* 24 */ "fnInt(",
    /* 25 */ "nDeriv(",
    /* 26 */ "",
    /* 27 */ "fMin(",
    /* 28 */ "fMax(",
    /* 29 */ " ",
    /* 2A */ "\"",
    /* 2B */ ",",
    /* 2C */ TITOKEN_i,
    /* 2D */ "!",
    /* 2E */ "CubicReg ",
    /* 2F */ "QuartReg ",
    /* 30 */ "0",
    /* 31 */ "1",
    /* 32 */ "2",
    /* 33 */ "3",
    /* 34 */ "4",
    /* 35 */ "5",
    /* 36 */ "6",
    /* 37 */ "7",
    /* 38 */ "8",
    /* 39 */ "9",
    /* 3A */ ".",
    /* 3B */ TITOKEN_E,
    /* 3C */ " or ",
    /* 3D */ " xor ",
    /* 3E */ ":",
    /* 3F */ "\n",
    /* 40 */ " and ",
    /* 41 */ "A",
    /* 42 */ "B",
    /* 43 */ "C",
    /* 44 */ "D",
    /* 45 */ "E",
    /* 46 */ "F",
    /* 47 */ "G",
    /* 48 */ "H",
    /* 49 */ "I",
    /* 4A */ "J",
    /* 4B */ "K",
    /* 4C */ "L",
    /* 4D */ "M",
    /* 4E */ "N",
    /* 4F */ "O",
    /* 50 */ "P",
    /* 51 */ "Q",
    /* 52 */ "R",
    /* 53 */ "S",
    /* 54 */ "T",
    /* 55 */ "U",
    /* 56 */ "V",
    /* 57 */ "W",
    /* 58 */ "X",
    /* 59 */ "Y",
    /* 5A */ "Z",
    /* 5B */ TITOKEN_THETA,
    /* 5C */ (const char *const) TI_TOKEN_MATRIX,
    /* 5D */ (const char *const) TI_TOKEN_LISTS,
    /* 5E */ (const char *const) tifileutils_tokens_83_5E,
    /* 5F */ "prgm",
    /* 60 */ (const char *const) TI_TOKEN_PIC,
    /* 61 */ (const char *const) TI_TOKEN_GDB,
    /* 62 */ (const char *const) tifileutils_tokens_83_62,
    /* 63 */ (const char *const) tifileutils_tokens_83_63,
    /* 64 */ "Radian",
    /* 65 */ "Degree",
    /* 66 */ "Normal",
    /* 67 */ "Sci",
    /* 68 */ "Eng",
    /* 69 */ "Float",
    /* 6A */ "=",
    /* 6B */ "<",
    /* 6C */ ">",
    /* 6D */ TITOKEN_LTE,
    /* 6E */ TITOKEN_GTE,
    /* 6F */ TITOKEN_NOT_EQUAL,
    /* 70 */ "+",
    /* 71 */ "-",
    /* 72 */ "Ans",
    /* 73 */ "Fix ",
    /* 74 */ "Horiz",
    /* 75 */ "Full",
    /* 76 */ "Func",
    /* 77 */ "Param",
    /* 78 */ "Polar",
    /* 79 */ "Seq",
    /* 7A */ "IndpntAuto",
    /* 7B */ "IndpntAsk",
    /* 7C */ "DependAuto",
    /* 7D */ "DependAsk",
    /* 7E */ (const char *const) tifileutils_tokens_83_7E,
    /* 7F */ "",
    /* 80 */ "",
    /* 81 */ "",
    /* 82 */ "*",
    /* 83 */ "/",
    /* 84 */ "Trace",
    /* 85 */ "ClrDraw",
    /* 86 */ "ZStandard",
    /* 87 */ "ZTrig",
    /* 88 */ "ZBox",
    /* 89 */ "Zoom In",
    /* 8A */ "Zoom Out",
    /* 8B */ "ZSquare",
    /* 8C */ "ZInteger",
    /* 8D */ "ZPrevious",
    /* 8E */ "ZDecimal",
    /* 8F */ "ZoomStat",
    /* 90 */ "ZoomRcl",
    /* 91 */ "PrintScreen",
    /* 92 */ "ZoomSto",
    /* 93 */ "Text(",
    /* 94 */ " nPr ",
    /* 95 */ " nCr ",
    /* 96 */ "FnOn ",
    /* 97 */ "FnOff ",
    /* 98 */ "StorePic ",
    /* 99 */ "RecallPic ",
    /* 9A */ "StoreGDB ",
    /* 9B */ "RecallGDB ",
    /* 9C */ "Line(",
    /* 9D */ "Vertical ",
    /* 9E */ "Pt-On(",
    /* 9F */ "Pt-Off(",
    /* A0 */ "Pt-Change(",
    /* A1 */ "Pxl-On(",
    /* A2 */ "Pxl-Off(",
    /* A3 */ "Pxl-Change(",
    /* A4 */ "Shade(",
    /* A5 */ "Circle(",
    /* A6 */ "Horizontal ",
    /* A7 */ "Tangent(",
    /* A8 */ "DrawInv ",
    /* A9 */ "DrawF ",
    /* AA */ (const char *const) TI_TOKEN_STR,
    /* AB */ "rand",
    /* AC */ TITOKEN_PI,
    /* AD */ "getKey",
    /* AE */ "'",
    /* AF */ "?",
    /* B0 */ "-",
    /* B1 */ "int(",
    /* B2 */ "abs(",
    /* B3 */ "det(",
    /* B4 */ "identity(",
    /* B5 */ "dim(",
    /* B6 */ "sum(",
    /* B7 */ "prod(",
    /* B8 */ "not(",
    /* B9 */ "iPart(",
    /* BA */ "fPart(",
    /* BB */ (const char *const) tifileutils_tokens_83_BB,
    /* BC */ TITOKEN_SQRT "(",
    /* BD */ TITOKEN_CUBERT "(",
    /* BE */ "ln_(",
    /* BF */ TITOKEN_e "^(",
    /* C0 */ "log(",
    /* C1 */ TITOKEN_SUB_TEN "^(",
    /* C2 */ "sin(",
    /* C3 */ "sin" TITOKEN_SUP_N_ONE "(",
    /* C4 */ "cos(",
    /* C5 */ "cos" TITOKEN_SUP_N_ONE "(",
    /* C6 */ "tan(",
    /* C7 */ "tan" TITOKEN_SUP_N_ONE "(",
    /* C8 */ "sinh(",
    /* C9 */ "sinh" TITOKEN_SUP_N_ONE "(",
    /* CA */ "cosh(",
    /* CB */ "cosh" TITOKEN_SUP_N_ONE "(",
    /* CC */ "tanh(",
    /* CD */ "tanh" TITOKEN_SUP_N_ONE "(",
    /* CE */ "If ",
    /* CF */ "Then",
    /* D0 */ "Else",
    /* D1 */ "While ",
    /* D2 */ "Repeat ",
    /* D3 */ "For(",
    /* D4 */ "End",
    /* D5 */ "Return",
    /* D6 */ "Lbl ",
    /* D7 */ "Goto ",
    /* D8 */ "Pause ",
    /* D9 */ "Stop",
    /* DA */ "IS>(",
    /* DB */ "DS>(",
    /* DC */ "Input ",
    /* DD */ "Prompt ",
    /* DE */ "Disp ",
    /* DF */ "DispGraph",
    /* E0 */ "Output(",
    /* E1 */ "ClrHome",
    /* E2 */ "Fill(",
    /* E3 */ "SortA(",
    /* E4 */ "SortD(",
    /* E5 */ "DispTable",
    /* E6 */ "Menu(",
    /* E7 */ "Send(",
    /* E8 */ "Get(",
    /* E9 */ "PlotsOn ",
    /* EA */ "PlotsOff ",
    /* EB */ TITOKEN_LIST_L,
    /* EC */ "Plot1(",
    /* ED */ "Plot2(",
    /* EE */ "Plot3(",
    /* EF */ NULL,
    /* F0 */ "^",
    /* F1 */ TITOKEN_XRT,
    /* F2 */ "1-Var_Stats ",
    /* F3 */ "2-Var_Stats ",
    /* F4 */ "LinReg(a+bx) ",
    /* F5 */ "ExpReg ",
    /* F6 */ "LnReg ",
    /* F7 */ "PwrReg ",
    /* F8 */ "Med-Med ",
    /* F9 */ "QuadReg ",
    /* FA */ "ClrList ",
    /* FB */ "ClrTable",
    /* FC */ "Histogram",
    /* FD */ "xyLine",
    /* FE */ "Scatter",
    /* FF */ "LinReg(ax+b)",
};

const char *const *const TIFILEUTILS_TOKENS_83 = tifileutils_tokens_83;
